enum btype {DEFAULT, TWICE, WIDTH, SPEED, REVERSE, POS};
extern void block_step(void);
extern void pos_toggle(void);
extern int get_pos_flag(void);
extern void twice_toggle(void);
extern int get_twice_flag(void);
extern void width_toggle(void);
extern int get_width_flag(void);
extern void speed_toggle(void);
extern int get_speed_flag(void);
extern void reverse_toggle(void);
extern int get_reverse_flag(void);
